#!/usr/bin/env sh
: ${R8S_DIR:=$HOME/.r8s}
: ${R8S_BIN:=$R8S_DIR/bin}
: ${VERBOSITY:=0}
TARGET=$1

set -e
set -u

if type "$TARGET" > /dev/null; then
  if [ $VERBOSITY -gt '0' ]; then
    echo "$TARGET found in path"
  fi
  if [ ! -e $R8S_BIN/$TARGET ]; then
    ln -s $(which $TARGET) $R8S_BIN/$TARGET
    if [ $VERBOSITY -gt '0' ]; then
      ls -al $R8S_BIN/$TARGET
    fi
  fi
else
  if [ $VERBOSITY -gt '0' ]; then
    echo "$TARGET not found attempting to make..."
  fi
    make -e $R8S_BIN/$TARGET
fi
